### ISSUE TITLE
Update for lua 5.2

### ISSUE THREAD

**Issue by daurnimator** [msva/lua-fann#2]
Compiling:

> $ sudo luarocks install https://rocks.moonscript.org/manifests/mva/lua-fann-0.4-1.rockspec
> Using https://rocks.moonscript.org/manifests/mva/lua-fann-0.4-1.rockspec... switching to 'build' mode
> Archive:  0.4.zip
> 54cb67f2e23b5210569392b76a72c068df649fc1
>    creating: lua-fann-0.4/
>   inflating: lua-fann-0.4/.config
>   inflating: lua-fann-0.4/.gitignore
>   inflating: lua-fann-0.4/COPYING
>   inflating: lua-fann-0.4/Makefile
>   inflating: lua-fann-0.4/README.md
>   inflating: lua-fann-0.4/TODO
>   inflating: lua-fann-0.4/doc.lua
>    creating: lua-fann-0.4/rockspecs/
>   inflating: lua-fann-0.4/rockspecs/lua-fann-0.4-1.rockspec
>   inflating: lua-fann-0.4/rockspecs/lua-fann-scm-0.rockspec
>    creating: lua-fann-0.4/src/
>   inflating: lua-fann-0.4/src/fann.c
>   inflating: lua-fann-0.4/src/fann.h
>    creating: lua-fann-0.4/test/
>   inflating: lua-fann-0.4/test/module.lua
>   inflating: lua-fann-0.4/test/xor.data
>   inflating: lua-fann-0.4/test/xortest.data
> gcc -O2 -fPIC -I/usr/include -c src/fann.c -o src/fann.o
> gcc -shared -o fann.so -L/usr/lib src/fann.o -lfann
> Updating manifest for /usr/lib/luarocks/rocks-5.2
> lua-fann 0.4-1 is now built and installed in /usr (license: MIT/X11)

First error:

> $ lua5.2 -e 'require "fann"'
> lua5.2: error loading module 'fann' from file '/usr/lib/lua/5.2/fann.so':
>        /usr/lib/lua/5.2/fann.so: undefined symbol: luaL_register
> stack traceback:
>        [C]: in ?
>        [C]: in function 'require'
>        (command line):1: in main chunk
>        [C]: in ?

**Comment by msva** [comment]
yeah. It requires to rewrite it to new Lua API, but, unfortunatelly, I've no time at the moment to take a look on all API changes and rewriting them. But I'd be glad to accept pull-request, if any 😀

**Comment by daurnimator** [comment]
I was just poking around for @theepicsnail. If you don't support 5.2, can you remove it from the rockspec?

**Comment by msva** [comment]
@daurnimator I, actually almost "fixed" (temporary) by defining LUA_COMPAT_MODULE, but discovered, that it is not enough for lua5.3 ;)
I'll fix 5.3 now and fix rockspecs

**Comment by msva** [comment]
uhm... Lua5.3 needs LUA_COMPAT_5_1 in addition to it's default LUA_COMPAT_5_2 at build time for that to work :-1:

**Comment by msva** [comment]
Anyway, I think, for now, I leave it with COMPAT_MODULE defined, but will remember to properly rewrite it for new APIs

**Comment by daurnimator** [comment]
> Anyway, I think, for now, I leave it with COMPAT_MODULE defined, but will remember to properly rewrite it for new APIs

not much will have changed....
- `luaL_register` should be replaced with `luaL_newlib`
- example updated to not use global `fann`

Other misc changes you could do:
- `if(!lua_isnumber(L,2))
      luaL_error(L, "Second argument to fann.create_sparse() must be an integer");` => `luaL_argcheck` + `lua_isinteger`
- replace `calloc` with userdata (that way you get cleanup for free)

**Comment by msva** [comment]
any more suggestions? :D

**Comment by daurnimator** [comment]
> any more suggestions? :D
- Fix rockspec to support 5.3 (operator you edited is incorrect)
- `lua_newtable` + `luaL_setfuncs` is available as the handy shortcut [`luaL_newlib`](http://www.lua.org/manual/5.3/manual.html#luaL_newlib)
- `lua_newuserdata` can never fail (e.g. you can remove https://github.com/msva/lua-fann/blob/1a9b5b398a82ea82aec5270d80284bca75910d4d/src/fann.c#L172)
